insertPragma: false
jsxBracketSameLine: false
proseWrap: preserve
quoteProps: as-needed
requirePragma: false
trailingComma: 'all'
useTabs: false
htmlWhitespaceSensitivity: 'css'
tabWidth: 2
printWidth: 80
semi: true
singleQuote: true
jsxSingleQuote: true
bracketSpacing: true
arrowParens: avoid
endOfLine: lf
